Cats/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :cats
end

Cats/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Cats/app/models/cat.rb
# == Schema Information
#
# Table name: cats
#
#  id          :bigint           not null, primary key
#  birth_date  :date             not null
#  color       :string           not null
#  name        :string           not null
#  description :text             not null
#  sex         :string(1)        not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Cat < ApplicationRecord
    include ActionView::Helpers::DateHelper

    VALID_COLORS = %w(black grey white orange brown)
    VALID_SEX = %w(M F)

    validates :birth_date, :color, :name, :description, :sex, presence: true
    validates :color, inclusion: { in: VALID_COLORS, message: "%{value} is not a valid color" }
    validates :sex, inclusion: { in: VALID_SEX, message: "%{value} is not a valid sex" }

    has_many :rental_requests,
    primary_key: :id,
    foreign_key: :cat_id,
    class_name: :CatRentalRequest,
    dependent: :destroy


    def age
        distance_of_time_in_words(birth_date, Time.now)                                               
    end

    def colors
        VALID_COLORS
    end
end

Cats/app/models/cat_rental_request.rb
# == Schema Information
#
# Table name: cat_rental_requests
#
#  id         :bigint           not null, primary key
#  cat_id     :integer          not null
#  start_date :date             not null
#  end_date   :date             not null
#  status     :string           default("PENDING")
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class CatRentalRequest < ApplicationRecord

    VALID_STATUS = %w(PENDNG APPROVED DENIED)
    validates :status inclusion: { in: VALID_STATUS, message: "%{value} is not a valid status" }
    validates :start_date, :end_date, :cat_id, :status, presence: true

    belongs_to :cat,
    primary_key: :id,
    foreign_key: :cat_id,
    class_name: :Cat

    def overlapping_requests
        requests = self.cat.cat_rental_requests
    end


end

Cats/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

Cats/app/controllers/cats_controller.rb
class CatsController < ApplicationController

    def index
        @cats = Cat.all
        render :index
    end

    def show
        @cat = Cat.find(params[:id])
        render :show
    end

    def new
        @cat = Cat.new
        render :new
    end

    def edit
        @cat = Cat.find(params[:id])
        render :edit
    end

    def update
        @cat = Cat.find(params[:id])

        if @cat.update(cat_params)
            redirect_to cat_url(@cat)
        else
            @cat.errors.full_messages
        end
    end

    def create
        @cat = Cat.new(cat_params)
        if @cat.save
            redirect_to cat_url(@cat)
            return
        else
            @cat.errors.full_messages
        end
        render :new

    end

    private

    def cat_params
        params.require(:cat).permit(:name, :birth_date, :color, :sex, :description)
    end


end

Cats/app/helpers/application_helper.rb
module ApplicationHelper
end

Cats/app/views/cats/_form.html.erb
<% action = cat.persisted? ? cat_url(@cat) : cats_url %>
<% button_text = cat.persisted? ? "Edit Cat" : "Add Cat" %>


<form method="POST" action='<%= action %>'> 
    <% if cat.persisted? %>
        <input type="hidden" name="_method" value="PATCH">
    <% end %>

    <label for="cat_name">Name</label>
    <input id="cat_name" type="text" name="cat[name]" value="<%= @cat.name %>">
    <br>

    <label for="cat_sex">Sex:</label>
    <input id="cat_sex" type="radio" name="cat[sex]" value="M" <%=@cat.sex == "M" ? "checked" : "" %>>Male
    <input id="cat_sex" type="radio" name="cat[sex]" value="F" <%=@cat.sex == "F" ? "checked" : ""  %>>Female
    <br>

    <select name="cat[color]">
        <% unless cat.persisted? %>
            <option selected disabled>--Select Color--</option>
        <% end %>
        <% @cat.colors.each do |color| %>
            <option <%= @cat.color == color ? "selected" : "" %>value="<%= color %>"> <%= color %> </option>
        <% end %>
    </select>
    <br> 

    <label for="cat_birth_date">Birth Date</label>
    <input type="date" id="cat_birth_date" name="cat[birth_date]" value="<%= @cat.birth_date %>">
    <br>

    <label for="cat_description">Cat Description</label>
    <textarea id="cat_description" type="textarea" name="cat[description]"><%= cat.persisted? ? @cat.description : "Describe cat here" %></textarea>
    <br>
    <br>

    <input type='submit' value="<%= button_text %>" >
</form>

Cats/app/views/cats/edit.html.erb
<h1>Edit Cat</h1>

<%= render 'form', cat: @cat %>

Cats/app/views/cats/index.html.erb
<h1> Here is all our cats: </h1>
<% @cats.each do |cat| %>
    <a href="<%= cat_url(cat) %>"> <%= cat.name %> </a>
    <br/>
<% end %>

Cats/app/views/cats/new.html.erb
<h1>Create new Cat</h1>

<%= render 'form', cat: @cat %>

Cats/app/views/cats/show.html.erb
<table>
    <thead>
        <tr>
            <th colspan="2"><%=@cat.name.capitalize%></th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>Attribute</td>
            <td>Value</td>
        </tr>
        <tr>
            <td>AGE</td>
            <td><%=@cat.age%> old </td>
        </tr>
          <tr>
            <td>Birth Date</td>
            <td><%=@cat.birth_date%></td>
        </tr>
         <tr>
            <td>Color</td>
            <td><%=@cat.color%></td>
        </tr>
         <tr>
            <td>Sex</td>
            <td><%=@cat.sex%></td>
        </tr>
        
    </tbody>
</table>

Cats/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cats</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>